### ISSUE TITLE
USB LangID is not provided by board. 

### ISSUE THREAD

**Issue by trickeydan** [j5api/sr-servo-v4-fw#5]
This breaks standard USB libraries!

```
Testing SR v4 MotorBoard.
Traceback (most recent call last):
  File "tests_hw/test_servo_board.py", line 37, in <module>
    r = Robot()
  File "/home/dan/Code/j5/j5/base_robot.py", line 22, in __new__
    obj.__init__(*args, **kwargs)  # type: ignore
  File "tests_hw/test_servo_board.py", line 27, in __init__
    HardwareEnvironment.get_backend(ServoBoard),
  File "/home/dan/Code/j5/j5/boards/board.py", line 80, in __init__
    self.update_boards()
  File "/home/dan/Code/j5/j5/boards/board.py", line 85, in update_boards
    discovered_boards = self._backend_class.discover()
  File "/home/dan/Code/j5/j5/backends/hardware/j5/raw_usb/raw_usb.py", line 64, in catch_exceptions
    return func(*args, **kwargs)
  File "/home/dan/Code/j5/j5/backends/hardware/sr/v4/servo_board.py", line 39, in discover
    board = ServoBoard(backend.serial, backend)
  File "/home/dan/Code/j5/j5/backends/hardware/j5/raw_usb/raw_usb.py", line 64, in catch_exceptions
    return func(*args, **kwargs)
  File "/home/dan/Code/j5/j5/backends/hardware/j5/raw_usb/raw_usb.py", line 98, in serial
    return self._usb_device.serial_number  # type: ignore
  File "/home/dan/.cache/pypoetry/virtualenvs/j5-py3.7/lib/python3.7/site-packages/usb/core.py", line 830, in serial_number
    self._serial_number = util.get_string(self, self.iSerialNumber)
  File "/home/dan/.cache/pypoetry/virtualenvs/j5-py3.7/lib/python3.7/site-packages/usb/util.py", line 314, in get_string
    raise ValueError("The device has no langid")
ValueError: The device has no langid
```

**Comment by kierdavis** [comment]
Note that this error message may also be caused by operating system permissions: pyusb/pyusb#139. It's possible the USB device is not at fault here.

This needs investigation.

**Comment by kierdavis** [comment]
Context: USB devices provide a set of *string descriptors*, each of which contains a textual piece of information (e.g. manufacturer name or serial number) along with some metadata. This string may be available in multiple languages. Requests for a string descriptor include a 16-bit number called the *langid*, which specifies which language to return the string in. The string descriptor with index 0 is a special case; it is available in any language and its content is an array of the langids supported by the device. [(source)](https://www.keil.com/pack/doc/mw/USB/html/_u_s_b__string__descriptor.html)

The somewhat misinformative "ValueError: The device has no langid" error shown above is [raised](https://github.com/pyusb/pyusb/blob/161086a/usb/util.py#L301) when the [array of supported langids](https://github.com/pyusb/pyusb/blob/161086a/usb/core.py#L791) is empty or could not be [retrieved](https://github.com/pyusb/pyusb/blob/161086a/usb/util.py#L222).

Avenues for investigation:
* Trace [`Device.langids`](https://github.com/pyusb/pyusb/blob/161086a/usb/core.py#L791) and [`get_langids`](https://github.com/pyusb/pyusb/blob/161086a/usb/util.py#L222) to work out why the langid array seems to be empty.
* Sniff the USB traffic between pyusb and the device (Wireshark can do this) to see whether the array is actually empty or if pyusb just thinks it is.
* Dig through the libopencm3 documentation and source code to find out how it handles langids. The firmware itself doesn't deal with them since it just [passes an array of string constants to libopencm3](https://github.com/j5api/sr-servo-v4-fw/blob/32d2bff/sbusb.c#L230) and lets it figure out how to turn them into string descriptors.

**Comment by kierdavis** [comment]
Raised upstream at https://github.com/srobo/servo-v4-fw/issues/11.
